info:
  app:
    desc: Internet Movie Graph Database
    name: IMGDB Service
    version: 1.0
    license: Lunatech
    contact:
      email: info@IMGDB.nl
      name: lunatech
      url: http://www.IMGDB.nl
spring:
  data:
    neo4j:
      username: neo4j
      password: admin
      uri: bolt://185.134.23.58:7687
  profiles:
    active: test
server:
  port: 5002
logging:
  level:
    root: debug
    org.springframework.web: debug

